server:
  port: 8002

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/link?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
#spring:
#  application:
#    name: short-link-admin
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#short-link:
#  group:
#    max-num: 20
#  flow-limit:
#    enable: true
#    time-window: 1
#    max-access-count: 20